### ISSUE TITLE
napari-PHILOW IndexError: list index out of range

### ISSUE THREAD

**Issue by keesh0** [neurobiology-ut/PHILOW#49] opened 2023-12-20 23:43 UTC
Hello,
I am exploring napari-PHILOW to train a with 12 images and corresponding masks (all png).
The masks are label images created using Napari.
Y:\data\soup\images\napari-PHILOW\mask
`
,filename,train
0,000.png,Not Checked
1,001.png,Not Checked
2,002.png,Not Checked
3,003.png,Not Checked
4,004.png,Not Checked
5,005.png,Not Checked
6,006.png,Not Checked
7,007.png,Not Checked
8,008.png,Not Checked
9,009.png,Not Checked
10,010.png,Not Checked
11,011.png,Not Checked
`

Any ideas on how to resolve the following error?
`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File ~\.conda\envs\napari4\lib\site-packages\napari_philow\_trainer.py:190, in Trainer.trainer(self=<napari_philow._trainer.Trainer object>)
    187 else:
    188     train_names = names
--> 190 w, h = Image.open(os.path.join(self.opath, names[0])).size
        self = <napari_philow._trainer.Trainer object at 0x000001DA88BF0EE0>
        names = []
        self.opath = 'Y:/data/GMI/soup/images/napari-PHILOW/orig'
        Image = <module 'PIL.Image' from 'C:\\Users\\keesh\\AppData\\Roaming\\Python\\Python39\\site-packages\\PIL\\Image.py'>
        os.path = <module 'ntpath' from 'C:\\Users\\keesh\\.conda\\envs\\napari4\\lib\\ntpath.py'>
    192 batch_size = min(math.ceil(len(train_names) / 10), 4)
    193 print('batchsize = ', batch_size)

IndexError: list index out of range`

**Comment by hiroalchem** [comment] 2023-12-21 05:31
@keesh0 
Thank you for using our PHILOW. Looking at the information in the CSV file you have provided, it appears that all images are marked as 'Not Checked'. 
Please note that data marked as 'Not Checked' is not used for training, which might be the cause of the issue. As described here: [https://github.com/neurobiology-ut/PHILOW#select-training-dataset](https://github.com/neurobiology-ut/PHILOW#select-training-dataset), could you please click on the button saying 'Not Checked' to change it to 'Checked' for the images you want to use for training? You may also directly modify the CSV file to change them to 'Checked'. 
Please give it a try.

**Comment by keesh0** [comment] 2023-12-22 01:49
Thanks, your suggestion worked well.
For people that skip Annotation Mode and use their own labeled data, maybe add an improved error message like:
"Did you forget to mark your data as Checked?".

**Comment by hiroalchem** [comment] 2023-12-31 04:47
@keesh0 Thank you for your suggestion. We will consider adding that feature in the next update.

**Closed as completed by hiroalchem** 2023-12-31 04:47 UTC
